### ISSUE TITLE
Make sheet available to move up when it is obstructed by keyboard

### ISSUE THREAD

**Issue by Tumist76** [BendixMa/sliding-sheet#10]
I've met a deadlock right now, trying to use a TextForm in a modal sheet. As you can see on the images below, the keyboard covers the view and it's not possible anymore to see the content of the form. Is it possible for the sheet to accommodate those changes and move the sheet itseft higher in those cases?

![InkedScreenshot_20200310-163309_LI](https://user-images.githubusercontent.com/2943278/76299892-6be30500-62ee-11ea-83f4-a545596f3c26.jpg)
![Screenshot_20200310-163314_2](https://user-images.githubusercontent.com/2943278/76299895-6c7b9b80-62ee-11ea-94e1-8d924c9e03fe.png)

**Comment by BendixMa** [comment]
I see. Haven't thought about that one. You might wanna try wrapping the sheet in a `Scaffold` using the `parentBuilder` and make sure that `resizeToAvoidBottomInset` is true. If that doesn't work you could add a `FocusNode` to the form field and add the keyboard height as a padding to the sheet when it becomes focused. 

I'm currently very busy and not able to fix it until next week if those steps don't work.

**Comment by BendixMa** [comment]
Fixed in version `0.2.9`.
