### ISSUE TITLE
Is it possible to make it so the leading space of a PanelHeaderWidget is not used?

### ISSUE THREAD

**Issue by GroovinChip** [BendixMa/sliding-sheet#14]
Currently, even without a specified leading widget, there is space allocated for it on the PanelHeaderWidget. I am not able to get the headerContent to take up the whole width of the PanelHeaderWidget.

**Comment by GroovinChip** [comment]
![Screenshot](https://i.imgur.com/SboN67n.png)

**Comment by GroovinChip** [comment]
![Screenshot](https://i.imgur.com/o5ZdoPE.png)

**Comment by BendixMa** [comment]
Could you please provide some code and explain what you mean with the `PanelHeaderWidget`?

**Comment by GroovinChip** [comment]
Oh shit. I filed these issues on the wrong package: I mean to file on sliding_panel. The names are so similar. I'm sorry!
