### ISSUE TITLE
Sliding panel body after opening keyboard its height get subtracted from a specific height

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [BendixMa/sliding-sheet#17]
This issue shows up when the panel has a text field inside its body, After opening keyboard the avoiding bottom insets working well but the panel body height get subtracted from a specific height about 50px compared to the panel body original height before opening the keyboard, This subtracted space get removed after first snaping after opening keyboard but this is not wanted.

This is a video gif for the issue.
![ezgif-6-6781ea3d11bd](https://user-images.githubusercontent.com/52201392/77960517-bb5a9680-72d8-11ea-80bc-62ac8865cb15.gif)

**Comment by BendixMa** [comment]
I think I fixed in version `0.2.11`. You might wanna check it out and see if it works now.

**Comment by AlaaEldeenYsr** [comment]
Alright it's working well thank very mush, See you next issue.

**Comment by BendixMa** [comment]
Ok, see you then.
