### ISSUE TITLE
Feature Request: Preventing panel from closing

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [BendixMa/sliding-sheet#19]
I show the panel to the user and it shouldn't be closed until he does some thing, So it will be great if you provided a parameter for preventing the panel from closing.
```
return GestureDetector(
      onVerticalDragStart: (details) {
        start = details.localPosition.dy;
        end = start;
      },
      onVerticalDragUpdate: (details) {
        end = details.localPosition.dy;
        final delta = swapSign(details.delta.dy);
        controller.imitiateDrag(delta);
      },
      onVerticalDragEnd: (details) {
        final velocity = swapSign(details.velocity.pixelsPerSecond.dy);
        onDragEnd(velocity);
      },
      onVerticalDragCancel: onDragEnd,
      child: child,
    );
```
I can see here that you handle the panel snaping through that gesture detector, So It will be great if you divided the onVerticalDragUpdate delta dy by a specific number so the panel be prevented from closing in a nice way like this
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/52201392/78053162-7ab65800-7380-11ea-8bc6-b0f431f085e6.gif)

And on the onVerticalDragEnd it will be great if you let me execute my callback so i can tell the user please fill the text fields first

**Comment by BendixMa** [comment]
That `GestureDetector `is actually just delegating the touch events from possible headers or footers the user might have, but I think that this is a good new feature. I will implement this, however I cannot say when I find enough time to do so.

You're using the sheet as a bottom sheet right? I think this issue will only be relevant for bottom sheets as a normal `SlidingSheet` is not closeable by nature.

**Comment by AlaaEldeenYsr** [comment]
In my case i use the showSlidingBottomSheet function which push a route bottom sheet in a forced way to the user and i don't want him to close it until he do what i want him to do. But ok take your time and also i will try to make it and see if i can make a pull request to you.

**Comment by BendixMa** [comment]
I added some commits on the dev branch that has a preview implementation of this feature. You can check it out by changing the pub dependency to:

~~~yaml
sliding_sheet:
    git:
      url: https://github.com/BendixMa/sliding-sheet
      ref: dev
~~~

Here is a demo of how this currently looks like:

![](https://github.com/BendixMa/sliding-sheet/blob/dev/assets/non_dismissable_demo.gif?raw=true)

I added the `isDismissable` flag on the `showSlidingBottomSheet` function. If it's set to false, the sheet won't be dismissable. Then there is also the `onDismissPrevented` callback that can be set to listen for when a user tried to dismiss the sheet. 

In order to change the `isDismissable` flag though, you will need to assign a `SheetController` on the dialog and call `rebuild()` on it when you want to change the `isDimissable` flag as `setState `or so wont work with dialogs. Here is the code of the example shown for how this would look like currently:

~~~dart
Future<void> showBottomSheet(BuildContext context) async {
  final theme = Theme.of(context);
  final textTheme = theme.textTheme;

  final controller = SheetController();
  bool isDismissable = false;

  await showSlidingBottomSheet(
    context,
    // The parentBuilder can be used to wrap the sheet inside a parent.
    // This can be for example a Theme or an AnnotatedRegion.
    parentBuilder: (context, sheet) {
      return Theme(
        data: ThemeData.dark(),
        child: sheet,
      );
    },
    // The builder to build the dialog. Calling rebuilder on the dialogController
    // will call the builder, allowing react to state changes while the sheet is shown.
    builder: (context) {
      return SlidingSheetDialog(
        controller: controller,
        duration: const Duration(milliseconds: 800),
        snapSpec: const SnapSpec(
          snap: true,
          snappings: [
            0.0,
            0.4,
            1.0,
          ],
        ),
        color: Colors.teal,
        maxWidth: 500,
        isDismissable: isDismissable,
        onDismissPrevented: () {
          HapticFeedback.heavyImpact();
          print('Dismiss prevented');
        },
        builder: (context, state) {
          return Container(
            padding: const EdgeInsets.all(32),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text(
                  'Confirm purchase',
                  style: textTheme.headline4.copyWith(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 16),
                Row(
                  children: <Widget>[
                    Expanded(
                      child: Text(
                        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sagittis tellus lacus, et pulvinar orci eleifend in.',
                        style: textTheme.subtitle1.copyWith(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    const SizedBox(width: 24),
                    Icon(
                      isDismissable ? Icons.check : Icons.error,
                      color: Colors.white,
                      size: 56,
                    ),
                  ],
                )
              ],
            ),
          );
        },
        footerBuilder: (context, state) {
          return Container(
            color: Colors.teal.shade700,
            padding: const EdgeInsets.all(16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: <Widget>[
                FlatButton(
                  onPressed: () => Navigator.pop(context),
                  child: Text(
                    'Cancel',
                    style: textTheme.subtitle1.copyWith(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                FlatButton(
                  onPressed: () {
                    if (!isDismissable) {
                      isDismissable = true;
                      controller.rebuild();
                    } else {
                      Navigator.pop(context);
                    }
                  },
                  child: Text(
                    'Approve',
                    style: textTheme.subtitle1.copyWith(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      );
    },
  );
}
~~~

I'm not yet sure on how we should handle back presses though. Currently the sheet wont be dismissed when the user presses the back button, however I'm not sure if we should leave it like so.

**Comment by AlaaEldeenYsr** [comment]
Wow i'm so happy, You are really awesome bro.
No problem with the onWillPop i think we can show a toast message or something.
But it would be better of course if the same animation happened on the willPopScope, I think we can do something like this for example, What do you think ?
```
showSlidingBottomSheet(
        context,
        useRootNavigator: true,
        parentBuilder: (cts, sheet) {
          return WillPopScope(
            onWillPop: () async {
              sheetController.snapToExtent(0.5).then((s) {
                sheetController.expand();
              });
              return false;
            },
            child: Scaffold(
              body: sheet,
            ),
          );
        },
```

**Comment by BendixMa** [comment]
Yea, I guess your right and it's probably better if the developer can decide for himself what he wants to do when the user presses the back button or the `backDrop`. I changed the callback function so that it now accepts two boolean flags that indicate whether the sheet prevented a dismiss from a back button press or a `backDrop` tap. Then the dev can decide to do whatever he wants with that information, for example as you to run said a animation.

Here is an example of how the callback might look like:
~~~dart
onDismissPrevented: (backButton, backDrop) async {
  HapticFeedback.heavyImpact();

  if (backButton || backDrop) {
    const duration = Duration(milliseconds: 300);
    await controller.snapToExtent(0.2, duration: duration, clamp: false);
    await controller.snapToExtent(0.4, duration: duration);
    // or Navigator.pop(context);
  }

  // Or pop the route
  // if (backButton) {
  //   Navigator.pop(context);
  // }

  print('Dismiss prevented');
}
~~~

If you want to try it out you might need to remove the `pubspec` dependency and add it again for changes to have effect.

**Comment by AlaaEldeenYsr** [comment]
It works, I hope that the new feature didn't make a problem with another thing but don't worry if i found some thing wrong you will see me at once, Alright bro i really appreciate your efforts responding to requested new features, However there is also another new feature do you think me to open a new issue for it and you close this one or to mention it here ?

**Comment by BendixMa** [comment]
It's probably better if we separate those issues, so please create a new issue if you have another request.

I'm gonna leave this issue open and the feature on the dev branch for now, so we can wait a few more days to ensure that everything's working as it should and then I'm gonna merge and publish it to pub.

**Comment by AlaaEldeenYsr** [comment]
I don't know exactly if this is an issue or it shouldn't be a one, It happens when i try to close the panel in a rapid continuous movements, As you see its animation not smooth in this case it's something like laggy or something ,The dismissable option is enabled, for me i see that the functionality working in general, But what do you think ?

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/52201392/78399236-d4bf5380-75f4-11ea-930c-5c53517e7e55.gif)

**Comment by AlaaEldeenYsr** [comment]
Another issue showed up, when i disable the dismissOnBackdropTap option the panel get closed when i press on the backdrop area, I think it shouldn't while that option is disabled.

**Comment by BendixMa** [comment]
I think both issues should be resolved now. Of course, there might be some lag when the user very rapidly flings back and forth but I hope I was able to reduce the lag a bit.

**Comment by AlaaEldeenYsr** [comment]
> I think both issues should be resolved now. Of course, there might be some lag when the user very rapidly flings back and forth but I hope I was able to reduce the lag a bit.

Great, I think the rapid movements is working smoothly now thank you,

But if you looked here you might see something like an issue, when scrolling down to the bottom and then snapping the panel down you will see on the top of the panel that weird line.

![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/52201392/78450515-552a9680-767f-11ea-96d2-c1897a81f300.gif)

**Comment by BendixMa** [comment]
Did you set the color property of the `SlidingSheet`?

**Comment by AlaaEldeenYsr** [comment]
> Did you set the color property of the `SlidingSheet`?

No the panel state as it is from yesterday, however I have just set the color property to transparent and the top line no more appears but i think this is not a solution because also something weird is happening here, You will see the close button at the bottom of the panel which executes navigator.pop() its working well, But after scrolling the panel down to the bottom and then snapping the panel down till that top line appears the navigator.pop doesn't get executed until pressing the button twice or maybe three presses, And sometime after the first press the top line get disappeared and after the second press the navigator.pop get executed, I think it's related to the issue in my previous comment.

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/52201392/78450723-ffef8480-7680-11ea-865f-e546453db5d3.gif)

**Comment by AlaaEldeenYsr** [comment]
While no top line the navigator.pop get executed after first press normal, But while there is that top line the navigator.pop doesn't get executed until pressing twice, And that top line appears after scrolling the panel body down to the bottom then snapping or moving the whole panel down, And i don't think that this is related to the panel color property because just yesterday it was working well or that issue wasn't existed. I hope that the issue have got clarified to you well

**Comment by AlaaEldeenYsr** [comment]
And also i think that made a problem with the isBackdropInteractable option, You will find ( twice  ) word is remarkable in this issue.

![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/52201392/78451293-054ece00-7685-11ea-9882-ed7adf54ed27.gif)

**Comment by BendixMa** [comment]
Yea I also noticed that issue that after a snap, the scroll physics thinks were still scrolling. I think I found a fix to it although I am still unsure why exactly that happens. 

The issues with the line happens sometimes when the color property of the sheet is different from what you set on your content. So ideally you use the color property as the background of your content, instead of setting the color inside a child of the sheet.

**Comment by AlaaEldeenYsr** [comment]
Alright i can set the color property but now i think you aware that this is not a solution for the ( twice ) issue ?
I restarted the pub and now the snapping no more active? Would you revert last git commit so that issue wasn't existed till you can figure out what's happening, What do you think ?

**Comment by AlaaEldeenYsr** [comment]
Or no i think that in yesterday commit the issue was existed also Hhhhh
So take your time fixing it but don't go long please Hhhhh.

**Comment by BendixMa** [comment]
I am sorry dude, but I cannot reproduce this issue anymore.

<img width="250px" src="https://user-images.githubusercontent.com/43601200/78455033-47373e80-769c-11ea-997c-1064ce56b2c9.gif"/>

Are you sure you are using the latest version?

**Comment by AlaaEldeenYsr** [comment]
Alright the navigator.pop ( twice ) issue i think it's solved, but the ```isBackdropInteractable``` still as it is, It would be great if you fix this also i think it's the last one left, This exception fires on vertical drag up on the backdrop area, But in general i really appreciate your efforts and a great thanks to you.
```
═══════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/scroll_position_with_single_context.dart': Failed assertion: line 82 pos 12: 'activity.isScrolling': is not true.
════════════════════════════════════════════════════════════════════════════════
```

> ![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/52201392/78451293-054ece00-7685-11ea-9882-ed7adf54ed27.gif)

**Comment by AlaaEldeenYsr** [comment]
This feature request i think it's done we can continue the ```isBackdropInteractable``` in its own issue

**Comment by BendixMa** [comment]
Version 0.3.0 has these changes now included.

**Comment by brizaldi** [comment]
hello @bnxm, is there a way to do this (prevent panel from closing) when using `SlidingSheet()` as a widget? because currently `isDismissable` only available in `showSlidingBottomSheet`
