### ISSUE TITLE
Feature Request: Make the panel snappable through the backdrop area

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [BendixMa/sliding-sheet#20]
I can snap or move the panel through vertical dragging on the panel body, It would be nice if this is available on the backdrop area also.

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/52201392/78406685-7057c080-7603-11ea-82c9-e0a316707b04.gif)

I tried to make it here in a custom way 
```
  double startPoint;
  var position = 0.0;
  final counter = Observable(0);
  final controller = SheetController();
  _HoursState() {
    Future(() {
      showSlidingBottomSheet(
        context,
        useRootNavigator: true,
        parentBuilder: (ctx, sheet) => Scaffold(
          body: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onVerticalDragStart: (details) => startPoint = details.localPosition.dy,
            onVerticalDragUpdate: (details) {
              print('object');
              final distance = 1 - ((details.localPosition.dy - startPoint) / 100);
              if (distance < 0) {
                position = 0;
                controller.snapToExtent(0);
              } else if (distance > 1) {
                position = 1;
                controller.snapToExtent(1);
              } else {
                position = distance;
                controller.snapToExtent(distance);
              }
            },
            onVerticalDragEnd: (details) {
              if (position >= 0.5) {
                controller.expand();
                controller.snapToExtent(1);
              } else
                controller.collapse();
            },
            onTap: () => controller.collapse(),
            child: sheet,
          ),
        ),
        builder: (ctx) => SlidingSheetDialog( ...... )
```
But the results was very strange, Based on the gesture detector logic i think it should work, But what i found out that the provided method snapToExtent is using an animation controller and that produce an unexpected behavior with the gesture detector vertical drag update events is about a long delay at the panel moving. I think it should be handled with the addPixelDelta method in the _SheetExtent class.

**Comment by BendixMa** [comment]
Yeah this feature shouldn't be a problem. I added the `isBackdropInteractable` flag that can control whether gestures on the back drop should be delegated to the sheet. This should create the desired effect.

**Comment by BendixMa** [comment]
Could you maybe clone the repo from https://github.com/BendixMa/sliding-sheet/tree/dev and see if the bottom sheet dialog in the example application is working for you and/or modify it so that it produces the issues you are experiencing, because I cannot reproduce them sadly...

**Comment by AlaaEldeenYsr** [comment]
I cloned the package and did run the example in debug mode, i changed the snapSpec to ```const SnapSpec(snappings: [1]),```, And deleted the ```minHeight: 700,``` and deleted the footer, Now we have enough backdrop space to test, When i drag up on the backdrop area that exception keeps firing,
```
═══════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/scroll_position_with_single_context.dart': Failed assertion: line 82 pos 12: 'activity.isScrolling': is not true.
════════════════════════════════════════════════════════════════════════════════
```

![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/52201392/78457871-ac476000-76ad-11ea-9895-5e1be09daef6.gif)

That exception keeps firing while i'm dragging up on the backdrop area as you see in the gif, But it's not breaking the snapping when try to drag down again, But in my app when i drag up on the backdrop space that exception keeps firing and on extra thing happens, The backdrop area snapping become inactive till after first snap down again.

![78451293-054ece00-7685-11ea-9882-ed7adf54ed27](https://user-images.githubusercontent.com/52201392/78457928-1f50d680-76ae-11ea-8714-fc48c3cad2f9.gif)

And this is the pubspec in my app 
```
sliding_sheet:
    git:
      url: https://github.com/BendixMa/sliding-sheet
      ref: dev
```

**Comment by AlaaEldeenYsr** [comment]
Note: In the release mode this issue not existed and it's working well, But in the debug mode that exception doesn't seem to be good at all

**Comment by BendixMa** [comment]
Yea thanks for your efforts, it really helped. You might wanna try now again. I hope it works now after my latest commits, haha.

**Comment by AlaaEldeenYsr** [comment]
Yes it's working, And also the problem of the top line which appears after scrolling down then snapping down i think it disappeared, I think that the package is stable now after last changes, But we can wait more time so we can insure that there is no more issues related to last new features,
@BendixMa Really great thanks to your efforts.

**Comment by BendixMa** [comment]
Version 0.3.0 has these changes now included.
