### ISSUE TITLE
Feature Request: Parallax effect on the body when sliding up

### ISSUE THREAD

**Issue by fvisticot** [BendixMa/sliding-sheet#21]
Did you plan to implement a parallax effect of the body when sliding up the panel.
In case of a map (with marker on center), it can be interesting to "parallax slide up" the map when the user slide up the panel to keep the marker of the map visible.

**Comment by BendixMa** [comment]
Yea thats definitely a cool feature. I am currently working on a couple of new features on the dev branch and already made a preview implementation of this feature. You can check it out by replacing your pubspec dependency to this:

~~~yaml
sliding_sheet:
    git:
      url: https://github.com/BendixMa/sliding-sheet
      ref: dev
~~~

Basically you now have the `parallaxSpec` and `body` parameter on the `SlidingSheet` that you can use to create a parallax effect:

~~~dart
parallaxSpec: const ParallaxSpec(
  enabled: true,
  amount: 0.66,
  endExtent: 0.6,
),
~~~

This for example creates this effect:


<img width="356px" src="https://raw.githubusercontent.com/BendixMa/sliding-sheet/dev/assets/parallax_demo.gif" href/>

**Comment by BendixMa** [comment]
Version 0.3.0 has the parallax option now included.
