### ISSUE TITLE
Touch events not delegated for header

### ISSUE THREAD

**Issue by essarn** [BendixMa/sliding-sheet#22]
If an container with no color is built at the top of the header widget tree will the touch events not be delegated to the sheet. 

```dart
  headerBuilder: (context, state) {
    return Container(
      height: 56,
      width: double.infinity,
      alignment: Alignment.center,
      child: Container(
        width: 50.0,
        height: 2.5,
        decoration: BoxDecoration(
          color: Colors.grey[300],
          borderRadius: BorderRadius.all(Radius.circular(5.0)),
        ),
      ),
    );
  },
```

In the example above will the sheet only be scrollade by grabbing the second container and not the first one as should be the case.

**Comment by BendixMa** [comment]
Thanks for the issue!

 I released a new version (0.3.0) that should fix this. You might wanna try it now and see if it works...
