### ISSUE TITLE
[ issue ] The Panel is stuck to the bottom of the screen

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [BendixMa/sliding-sheet#30]

**Comment by AlaaEldeenYsr** [comment]
Forget the first comment i think it's not easy to reproduce the issue through it, So notice here it's easy to notice the issue from here, As you see there is a small part of the panel still stuck to the bottom screen, And that's make the screen behind not clickable because the panel route still there and not popped even if it should be popped because i dragged the panel down till bottom but it's stuck.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/52201392/79631899-47374400-815c-11ea-97e4-b6a8af141a8d.gif)

**Comment by BendixMa** [comment]
Yea I could reproduce that but it seems it only happens when trying to close the sheet using the backdrop without releasing the pointer. Could you switch to the dev branch again and see if it works now?

~~~yaml
sliding_sheet:
    git:
      url: https://github.com/BendixMa/sliding-sheet
      ref: dev
~~~

**Comment by AlaaEldeenYsr** [comment]
Alright the issue in the second comment is solved but the main issue in the first comment (removed) is still existed, I hope you can reproduce from the gif.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/52201392/79671330-ddee1a00-81c9-11ea-82c0-14f1e089ab76.gif)

**Comment by AlaaEldeenYsr** [comment]
Any updates here
@BendixMa

**Comment by BendixMa** [comment]
Could you try if it works now?

**Comment by AlaaEldeenYsr** [comment]
Yes it's solved i think, It's working well thanks to you. @BendixMa

**Comment by BendixMa** [comment]
It's now on pub under version 0.3.4
