### ISSUE TITLE
Does not support complete scrolling of content when Accessibility is set or have VERY LARGE FontSize

### ISSUE THREAD

**Issue by bpaul7101** [BendixMa/sliding-sheet#4]
This is a great Widget - thank you.

There are a couple of issues : 

1) If you display TEXT and set the FONT to very LARGE - you get overflow and the text does not SCROLL.

2) Does not support accessibility :  I've noticed that when the content that is placed in the sheet can be changed outside of the app (via accessibility changes) - then the height that is set to the container is not correctly adjusted. The content does not scroll ...

As an example - make your content have lots of TEXT and then change the ACCESSIBILITY to VERY LARGE text. You will see that your content either gives overflow (even if you wrap in a ScrollController) or else the text is trimmed and you do not see everything ....

**It scrolls properly with lots of text**
![image](https://user-images.githubusercontent.com/56043190/73608255-c59e3400-45b8-11ea-9baf-5df5106cf783.png)

**When ACCESSIBILITY/FONT increased - get issues**
![image](https://user-images.githubusercontent.com/56043190/73608271-f5e5d280-45b8-11ea-8b16-ebb48f27dc5b.png)

**Comment by BendixMa** [comment]
Does the problem persist even after you call `rebuild` on the sheet controller?

**Comment by bpaul7101** [comment]
Unfortunately - yes.

The only fix I have found is to use a unique Objectkey as a parameter to SlidingSheet - this therefore rebuilds each time but I shouldnt have to do this ....

**Comment by BendixMa** [comment]
Ok, I'll have a look at it in the coming days when I have some time to spare.

**Comment by bpaul7101** [comment]
Actually - I take that back. Setting ObjectKey has no effect.

The issue is because you define the height of the Container via MediaQuery.of(context).size. When you take this line out - you have NO OVERFLOW and LARGE TEXT fits - but the SHEET grows to only fit the accommodated size - meaning if you have a single LINE of text, the SHEET will be very small.

**Comment by bpaul7101** [comment]
Other than this issue - the plugin is excellent.

**Comment by BendixMa** [comment]
Hey I'm sorry but I just tested it and couldn't reproduce the issue with text and changing the font size to very large. Could you maybe provide some sample code of your sheet?    


> The issue is because you define the height of the Container via MediaQuery.of(context).size. 

About which `Container` and `MediaQuery` are you talking about here?

**Comment by bpaul7101** [comment]
Hi
Hopefully this diagram will make it clearer : 

![image](https://user-images.githubusercontent.com/56043190/73614756-e044cd00-45f9-11ea-9002-5bca06b768b3.png)

**Comment by BendixMa** [comment]
As you said the sheet sizes itself as big as it's child. If you set a fixed height on your child the sheet will also only take up the same height. And if the content of the `Container` is bigger than the fixed height, it overflows. So you would have to replace the `height` with the `constraints` parameter for your `Container` and set the `minHeight` for the `BoxConstraints` to whatever the minimum height of the sheet should be.

**Comment by alexda8999** [comment]
I have the same issue - the plugin fails in Tablet mode especially when you rotate - always get the same exception when try and rotate from portrait to landscape - hence plugin does not seem to support Tablet or more to the point rotation.

@bpaul7101 When I also set the size of the sheet via MediaQuery etc , and then enable Accessibility font size - I also get overflow.


![image](https://user-images.githubusercontent.com/60812592/74083462-3384a880-4a5c-11ea-93c3-cd7a5d5b7234.png)

**Comment by alexda8999** [comment]
@bpaul7101 

This works and doesnt have the issues that this plugin has : 

https://pub.dev/packages/solid_bottom_sheet
