### ISSUE TITLE
Sheet is dragged vertically when a child is dragged horizontally

### ISSUE THREAD

**Issue by rodrigoaddor** [BendixMa/sliding-sheet#6]
In a scrollable sheet with a horizontally scrollable child, when the child is scrolled, the sheet is also draggable. It makes so the sheet can be acidentally closed when scrolling the child.

When the sheet is scrolled a little bit, that behavior stops, and the child can be safely scrolled horizontally.

```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SlidingUpPanel(
      panelBuilder: (scroll) => SingleChildScrollView(
        controller: scroll,
        child: SizedBox(
          height: 600,
          child: ListView(
            scrollDirection: Axis.horizontal,
            children: [
              Placeholder(fallbackWidth: 500),
              Placeholder(fallbackWidth: 500),
            ],
          ),
        ),
      ),
    ),
  );
}

```

**Comment by BendixMa** [comment]
The sample code you provided is from another package. Holds that also true for my package or do you wanted to create the issue at https://github.com/akshathjain/sliding_up_panel?

**Comment by rodrigoaddor** [comment]
Oh, indeed. I was using your package before, and got them mixed up. Sorry for the confusion
