### ISSUE TITLE
showSlidingBottomSheet rootNavigator true 

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [BendixMa/sliding-sheet#9]
showSlidingBottomSheet instead of return navigator.push() return Navigator.of(context, rootNavigator: bool).push()

**Comment by BendixMa** [comment]
I'm sorry, but could you provide a bit more information about what your issue or question is?

**Comment by AlaaEldeenYsr** [comment]
I have two nested navigators inside the material app, I want to push the sliding sheet above the root navigator not above only the closest navigator relative to the context.
the Navigator.push() push the sliding_sheet above the closest navigator relative to the context, Which not taking the whole screen size.
![image](https://user-images.githubusercontent.com/52201392/75622445-fae27580-5ba8-11ea-8580-4f10b453ea2c.png)

But when i changed the code of your package(rootNavigator: true)
![image](https://user-images.githubusercontent.com/52201392/75622460-28c7ba00-5ba9-11ea-890b-94ad5e71d0b9.png)

The results was
![image](https://user-images.githubusercontent.com/52201392/75622470-4d239680-5ba9-11ea-8ee5-718025b817d5.png)

So it will be great if you handle a bool pramater for the rootNavigator

**Comment by BendixMa** [comment]
I see now. It definitely makes sense to be able to set that parameter and I just released a new version `(0.2.8)` that adds this feature by setting the `useRootNavigator` parameter of the `showSlidingBottomSheet` function.

**Comment by AlaaEldeenYsr** [comment]
@BendixMa You are awesome, Thank you bro.

**Comment by AlaaEldeenYsr** [comment]
Alright it's working well but most of the time it throws that exception and the sliding sheet not opened
════════ Exception caught by scheduler library ═════════════════════════════════
There are multiple heroes that share the same tag within a subtree.
══════════════════════════════════════════
![image](https://user-images.githubusercontent.com/52201392/75626458-68ee6300-5bd0-11ea-92e5-249c1d5ab4bb.png)
i'm sure that the issue comming from the package because when i push my body widget without the showSlidingBottomSheet it's working well, and the exception specificly comming from the useRootNavigator, Because it's working well when it's false

**Comment by BendixMa** [comment]
I'm not sure if I can help you on that one. Can you maybe try to get your hands on a more in depth stacktrace? Often times this issue appears when you have multiple `FloatingActionButtons` and didn't change their hero tag, however I will take a look at this when I find some time and see what I can do.

**Comment by AlaaEldeenYsr** [comment]
I'm sorry yeah the problem was from the FloatingActionButtons HreoTags, Thank you
